name: Bug Report
description: Create a report to help us improve
type: "Bug"
title: '...provide a title...'
projects: ["AlaskaAirlines/19"]
body:
  - type: checkboxes
    id: browsers
    attributes:
      label: What browser client(s) are you seeing the issue on?
      description: Select all that apply.
      options:
        - label: Firefox
        - label: Chrome
        - label: Safari
        - label: Microsoft Edge
  - type: checkboxes
    id: platform
    attributes:
      label: What devices platform(s) are you seeing the issue on?
      description: Select all that apply.
      options:
        - label: Desktop
        - label: Mobile
  - type: textarea
    id: details
    attributes:
      label: Steps to reproduce
      description: List out the steps to reproduce the behavior and include screenshots
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'

        Result:
        '... What happened that you didn't expect? ...'
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Please add a clear and concise description of what you expected to
        happen.
  - type: input
    id: version
    attributes:
      label: Which version of AuroDesignTokens do you have installed?
  - type: markdown
    attributes:
      value: >
        The current released version is:<br />[![See it on
        NPM!](https://img.shields.io/npm/v/@aurodesignsystem/AuroDesignTokens?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@aurodesignsystem/AuroDesignTokens)
  - type: checkboxes
    id: repro
    attributes:
      label: Reproducible on the Auro doc site
      options:
        - label: 'I am able to reproduce this issue on the [Auro doc site](https://auro.alaskaair.com).'
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria (To be determined by the Auro team)
      description: Define exit criteria for completing this feature request.
