name: Bug report
description: Create a report to help us improve
title: '[issue summary] Please verify version before submitting new issue'
labels:
  - 'Type: Bug'
  - not-reviewed
  - 'design tokens'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Please verify the version of Auro design tokens you have installed
  - type: markdown
    attributes:
      value: >
        [![See it on
        NPM!](https://img.shields.io/npm/v/@alaskaairux/design-tokens?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@alaskaairux/design-tokens)
  - type: textarea
    id: details
    attributes:
      label: Please describe the bug
      description: List out the steps to reproduce the behavior and include screenshots
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: dropdown
    id: repro
    attributes:
      label: Reproducing the error
      description: Are you able to reproduce this issue on the [Auro docsite](https://auro.alaskaair.com/)?
      options:
        - This issue is reproducible on the Auro docsite
        - This issue cannot be reproduced on the Auro docsite
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Please add a  clear and concise description of what you expected to
        happen.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: Define your issue's exit criteria
      placeholder: "This issue can be closed once the error has been corrected. Any additional scope e.g. updates or refactors, should be discussed PRIOR to adding scope to this issue."
