name: Feature Request
description: Suggest an idea for this project
type: "Feature"
title: '...provide a title...'
projects: ["AlaskaAirlines/19"]
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature addition or change is.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria (To be determined by the Auro team)
      description: Define exit criteria for completing this feature request.
