name: Feature request
description: Suggest an idea for this project
title: 'Auro design tokens: [feature summary]'
labels:
  - 'Type: Feature'
  - not-reviewed
  - 'design tokens'
body:
  - type: textarea
    id: request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: textarea
    id: exit-criteria
    attributes:
      label: Exit criteria
      description: Define your issue's exit criteria
      placeholder: "This issue can be closed once the error has been corrected. Any additional scope e.g. updates or refactors, should be discussed PRIOR to adding scope to this issue."
