name: General support
description: Suggestions that are not related to bugs or new features
title: 'Auro Design Tokens: [issue]'
labels:
  - 'Type: Question'
  - 'Type: Feature'
  - not-reviewed
  - 'design tokens'
body:
  - type: textarea
    id: request
    attributes:
      label: General Support Request
      description: A clear and concise description of what you are interested in seeing.
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: Not obligatory, but suggest an idea of how to implement the requested update.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
