name: Deploy Demo

on:
  pull_request:
    branches: [ main ]

jobs:

  call-publish-demo-workflow:
    uses: AlaskaAirlines/auro-library/.github/workflows/publishDemo.yml@main
    secrets:
      AURO_SURGE_TOKEN: ${{secrets.AURO_SURGE_TOKEN}}